### ISSUE TITLE
[Bug]: firewall icmp sends along ports parameter that is rejected by REST API

### ISSUE THREAD

**Issue by marcfiu** [linode/ansible_linode#191]
### Ansible Version

ansible [core 2.11.12] 

### Ansible Configuration

Note that `ansible-config dump --only-changed` shows nothing.

Using linode.cloud version 0.7.1 installed via ansible-galaxy collection.

Using linode-api4 version 5.2.1 installed via pip.

### Effected Components

firewall

### Expected Behavior

set ICMP rules

### Actual Behavior

Get the following error:
```
linode_api4.errors.ApiError: 400: Ports are not allowed for ICMP protocols;
```

### Steps to Reproduce

You can replicate the issue with the following playbook:
```
###
---
- name: "firewall setup"
  hosts: localhost
  tasks:   
  - name: "icmp test"
    linode.cloud.firewall:
      api_token: "YOURTOKEN"
      state: present
      label: "icmpacl"
      devices:
        - id: "YOUR LINODE ID"
          type: linode
      rules:
        outbound_policy: ACCEPT
        inbound_policy: DROP
        inbound:
          - label: "demo-icmp"
            addresses:
              ipv4: "{{ ['0.0.0.0/0'] }}"
              ipv6: "{{ ['::0/0'] }}"
            description: "Allow all icmp traffic"
            protocol: ICMP
            action: ACCEPT
```
