### ISSUE TITLE
[Feature]: ipaddress_info module

### ISSUE THREAD

**Issue by marcfiu** [linode/ansible_linode#212]
### Description

The `linode.cloud.instance_info` module only returns ipv4 addresses without its subnet mask info. While generally one can guess what it is today (ie., /24 for public ips and /17 for private), this feels suboptimal to make such assumptions in general. There does not appear a way to get further IP Address information along the lines of the [IP Address View](https://www.linode.com/docs/api/networking/#ip-address-view) API. This is a feature request to create a new `ipaddress_info` module that given a list of IP addresses, returns the info one can get using the IP Address View API.

### New/Affected Components

new component: ipaddress_info.py

### Example Ansible Config

```
- name: "Get IP address details"
   register: result
   linode.cloud.ipaddress_info:
       ips:
          - {{ address1 }}
          - {{ address2 }}
          - {{ addressN }}
```

The `result` would be a list ipaddress_info in the same order as requested, where each item in the list contains information as defined by the current [IP Address Response Detail](https://www.linode.com/docs/api/networking/#ip-address-view__responses)
