### ISSUE TITLE
[Feature]: support incremental firewall updates

### ISSUE THREAD

**Issue by marcfiu** [linode/ansible_linode#216]
### Description

The `linode.cloud.firewall` module makes wholesale changes to the firewall. This is fine when the user has simple firewall rules--eg., a single inbound rule. When there are many rules in ansible it requires a more complex loops/with_items pattern to make an incremental update--eg., adding or deleting an ip address, etc. The enhancement request is to support an "update" state that lets one make an incremental update to existing firewall rules.

### New/Affected Components

`linode.cloud.firewall`

### Example Ansible Config

Below is an example change that updates an IP address list of an existing inbound rule:
```
  - name: "update inbound ips for 'demo' FW device"
    linode.cloud.firewall:
      api_token: {{ my_token }}
      state: update
      label: "demo"
      rules:
        inbound:
        - label: "demo-tcpacl"
          addresses:
            ipv4: "{{ ips }}"
```

All other aspects of the firewall remain the same / unchanged.
