### ISSUE TITLE
[Bug]: Unsupported parameters for (linode.cloud.instance) module: configs.interfaces

### ISSUE THREAD

**Issue by svdo** [linode/ansible_linode#291]
### Ansible Version

ansible [core 2.14.2]

### Ansible Configuration

ANSIBLE_PIPELINING(/Users/[redacted]/deployment/ansible/ansible.cfg) = True
CONFIG_FILE() = /Users/[redacted]/deployment/ansible/ansible.cfg
LOCALHOST_WARNING(/Users/[redacted]/deployment/ansible/ansible.cfg) = False

### Effected Components

instance

### Expected Behavior

According to the docs (https://github.com/linode/ansible_linode/blob/main/docs/modules/instance.md#configs) I should be able to specify `interfaces` in `configs`; creating instances should work that way.

### Actual Behavior

I get the error:

```
Unsupported parameters for (linode.cloud.instance) module: configs.interfaces. Supported parameters include: comments, devices, helpers, kernel, label, memory_limit, root_device, run_level, virt_mode.
```

### Steps to Reproduce

This is from the role file in my playbook:

```
- name: Create a set of Linode instances in async
  linode.cloud.instance:
    label: "{{ env }}-{{ node_type }}-{{ '%02d' | format(node_index + 1) }}"
    type: "{{ node_config.type | default(linode.type) }}"
    region: "{{ node_config.region | default(linode.region) }}"
    booted: true
    tags: ["{{ env }}", "{{ node_type }}"]
    state: "{{ node_config.state }}"
    boot_config_label: boot-config
    disks:
      - label: boot
        image: "{{ node_config.image | default(linode.image) }}"
        size: "{{ linode.boot_disk_size }}"
        stackscript_id: "{{ linode.stackscript_id | int }}"
        stackscript_data: "{{ linode.stackscript_data }}"
      - label: swap
        filesystem: swap
        size: 512
    configs:
      - label: boot-config
        interfaces:
          - purpose: public
          - purpose: vlan
            label: "{{ env }}-swarm"
            ipam_address: "{{ vlan_ipam_prefix }}{{ node_index + 1 + (vlan_ip_offset | default(0)) }}/{{ vlan_ipam_subnet }}"
        root_device: /dev/sda
        devices:
          sda:
            disk_label: boot
          sdb:
            disk_label: swap
  when: node_config.state == 'present'
  # Let's create these instances in async to speed up provisioning times
  async: 120
  poll: 0
  changed_when: false
  loop: "{{ node_configs }}"
  loop_control:
    loop_var: node_config
    index_var: node_index
  register: instance_job

- name: Wait for all instances to be created
  ansible.builtin.async_status:
    jid: "{{ async_result_item.ansible_job_id }}"
  when: async_result_item.ansible_job_id is defined
  loop: "{{ instance_job.results }}"
  loop_control:
    loop_var: "async_result_item"
  register: instance_create
  until: instance_create.finished
  retries: 30
```

**Comment by svdo** [comment]
Please note that the same code but without `disks` and `configs` works as intended:

```
- name: Create a set of Linode instances in async
  linode.cloud.instance:
    label: "{{ env }}-{{ node_type }}-{{ '%02d' | format(node_index + 1) }}"
    type: "{{ node_config.type | default(linode.type) }}"
    region: "{{ node_config.region | default(linode.region) }}"
    image: "{{ node_config.image | default(linode.image) }}"
    booted: true
    tags: ["{{ env }}", "{{ node_type }}"]
    stackscript_id: "{{ linode.stackscript_id | int }}"
    stackscript_data: "{{ linode.stackscript_data }}"
    state: "{{ node_config.state }}"
    interfaces:
      - purpose: public
      - purpose: vlan
        label: "{{ env }}-swarm"
        ipam_address: "{{ vlan_ipam_prefix }}{{ node_index + 1 + (vlan_ip_offset | default(0)) }}/{{ vlan_ipam_subnet }}"
  when: node_config.state == 'present'
  # Let's create these instances in async to speed up provisioning times
  async: 120
  poll: 0
  changed_when: false
  loop: "{{ node_configs }}"
  loop_control:
    loop_var: node_config
    index_var: node_index
  register: instance_job

- name: Wait for all instances to be created
  ansible.builtin.async_status:
    jid: "{{ async_result_item.ansible_job_id }}"
  when: async_result_item.ansible_job_id is defined
  loop: "{{ instance_job.results }}"
  loop_control:
    loop_var: "async_result_item"
  register: instance_create
  until: instance_create.finished
  retries: 30
```
