### ISSUE TITLE
[Help]: 

### ISSUE THREAD

**Issue by grzegorzk** [linode/ansible_linode#332]
### Description

Each time I invoke `ansible-playbook` on my playbook I see log in Linode activity log of subject linode saying:

```
Config boot-config has been updated on Linode [gitlab](https://cloud.linode.com/linodes/44899779) by grzeg0rz.
```

Also ansible playbook results in below (suggesting something got changed)

```
PLAY RECAP *********************************************************************************************************************************************************************************************************************************
localhost                  : ok=5    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

Am I correct to expect no change applied to my linode if there was no change applied to playbook?

### Ansible Configuration

```
CONFIG_FILE() = /opt/ansible/ansible.cfg
DEFAULT_VAULT_PASSWORD_FILE(/opt/ansible/ansible.cfg) = /opt/ansible/.vault-pass
HOST_KEY_CHECKING(/opt/ansible/ansible.cfg) = False
```

### Attempted Config

```yaml
- name: Create empty Linode instance
  # https://github.com/linode/ansible_linode/blob/main/docs/modules/instance.md
  linode.cloud.instance:
    api_token: "{{ linode_api_token }}"
    label: my_first_instance
    type: g6-nanode-1
    region: eu-central
    booted: false
    boot_config_label: config
    tags:
      - "{{ general_tag }}"
    disks:
      - label: boot
        size: 256
        filesystem: raw
      - label: swap
        size: 2048
        filesystem: raw
      - label: root
        size: 23296
        filesystem: raw
    configs:
      - label: boot-config
        # https://api.linode.com/v4/linode/kernels?page=4
        kernel: linode/direct-disk
        root_device: /dev/sda
        devices:
          sda:
            disk_label: boot
          sdb:
            disk_label: swap
          sdc:
            disk_label: root
        helpers:
          devtmpfs_automount: false
          distro: false
          modules_dep: false
          network: false
          updatedb_disabled: false
        interfaces:
          - purpose: public
          - purpose: vlan
            label: "{{ general_vlan }}"
    state: present
  register: my_first_instance
```
