### ISSUE TITLE
[Help]: linode.cloud.api_request

### ISSUE THREAD

**Issue by grzegorzk** [linode/ansible_linode#334]
### Description

I'm trying to issue a task which would reboot my vm into rescue mode, but I'm getting error suggesting my JSON is incorrect. I'm pretty sure JSON is not missing double-quotes anywhere, so I must be doing something wrong and can't see where.

### Ansible Configuration

CONFIG_FILE() = /opt/ansible/ansible.cfg
DEFAULT_VAULT_PASSWORD_FILE(/opt/ansible/ansible.cfg) = /opt/ansible/.vault-pass
HOST_KEY_CHECKING(/opt/ansible/ansible.cfg) = False

### Attempted Config

Below fails with `fatal: [localhost]: FAILED! => {"changed": false, "msg": "JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)"}`:
```yml
# empty_linode registered earlier
- name: Boot empty linode into rescue mode
  # https://github.com/linode/ansible_linode/blob/dev/docs/modules/api_request.md
  linode.cloud.api_request:
    # https://www.linode.com/docs/api/linode-instances/#linode-boot-into-rescue-mode
    api_token: "{{ linode_api_token }}"
    path: "/linode/instances/{{ empty_linode.instance.id }}/rescue"
    method: POST
    body_json: >
      {
        "devices": {
          "sda": {
            "disk_id": {{ empty_linode.configs[0].devices.sda.disk_id }}
          }
        }
      }
  register: response
```

However below "works" (linode boots to rescue mode however no devices are mapped):
```yml
# empty_linode registered earlier
- name: Boot empty linode into rescue mode
  # https://github.com/linode/ansible_linode/blob/dev/docs/modules/api_request.md
  linode.cloud.api_request:
    # https://www.linode.com/docs/api/linode-instances/#linode-boot-into-rescue-mode
    api_token: "{{ linode_api_token }}"
    path: "/linode/instances/{{ empty_linode.instance.id }}/rescue"
    method: POST
    body_json: >
      {
        "devices": {
        }
      }
  register: response
```

I'm trying to use json above because below yml renders to json with strings as disk id (int is required), it would be nice if in this case strings could be converted to int when rendering to json
```yml
- name: Boot empty linode instance into rescue mode
  # https://github.com/linode/ansible_linode/blob/dev/docs/modules/api_request.md
  linode.cloud.api_request:
    # https://www.linode.com/docs/api/linode-instances/#linode-boot-into-rescue-mode
    api_token: "{{ linode_api_token }}"
    path: "/linode/instances/{{ empty_linode.instance.id }}/rescue"
    method: POST
    body:
      devices:
        sda:
          disk_id: "{{ empty_linode.configs.devices.sda.disk_id }}"
  register: response
```

**Comment by grzegorzk** [comment]
I have done some googling and found that `{{whatever}}` will always render as string (so wrapped within double-quotes) - I thought this would not be the case if I used template within string...

As a workaround I used below which works only because linode config registered earlier was using the same key for `disk_id` within `sda` which is also required within `sda` in `devices` for API call.

```yml
- name: Boot empty linode instance into rescue mode
  # https://github.com/linode/ansible_linode/blob/dev/docs/modules/api_request.md
  linode.cloud.api_request:
    # https://www.linode.com/docs/api/linode-instances/#linode-boot-into-rescue-mode
    api_token: "{{ linode_api_token }}"
    path: "/linode/instances/{{ empty_linode.instance.id }}/rescue"
    method: POST
    body:
      devices:
        sda: "{{ empty_linode.configs[0].devices.sda }}"
  register: response
```

I still think it would be nice if `linode.cloud.api_request` would cast values to proper types when rendering json from yml... though at least my immediate pain is solved.
