### ISSUE TITLE
[Help]: ansible & Lish console

### ISSUE THREAD

**Issue by grzegorzk** [linode/ansible_linode#398]
### Description

I would like to prepare my linode from the ground-up through Lish console. I was searching for appropriate command through Linode API and through linode collection, however I could find none.

Using Linode collection and also Linode API I can successfully create a linode and also I can successfully boot it into rescue mode. But beyond that I could find no solution which would allow me to automate my workflow. I would like to be able to ssh to my linode lish console so I can start proper ssh on it and then run commands through ansible builtins. Please accept my apologies if this is not the right place to ask this question, if so please close the issue and I'll keep pulling my hair out :)

### Ansible Configuration

CONFIG_FILE() = /opt/ansible/ansible.cfg
DEFAULT_VAULT_PASSWORD_FILE(/opt/ansible/ansible.cfg) = /opt/ansible/.vault-pass
HOST_KEY_CHECKING(/opt/ansible/ansible.cfg) = False

### Attempted Config

Here is my attempt:

```yml
- name: deployment
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../group_vars/vars.yml

  tasks:
    - include_tasks: ../tasks/create_instance.yml
      vars:
        label: my_first_linode
    - include_tasks: ../tasks/boot_instance_into_resuce_mode.yml
      vars:
        label: my_first_linode
    - include_tasks: ../tasks/provision_ssh_keys_through_lish.yml
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/ssh_connection.html
      vars:
        label: my_first_linode
        ansible_connection: ansible.builtin.ssh
        ansible_ssh_host: lish-ap-southeast.linode.com
        ansible_ssh_user: my_user_name
        ansible_ssh_common_args: "-t -o ControlMaster=auto -o ControlPersist=300s"
        ansible_ssh_timeout: 300
        connect_timeout: 30
```

Linode gets created and booted into rescue mode without any problem so I omitted those tasks.
Here is `provision_ssh_keys_through_lish.yml`:

```yml
- name: connect console through lish
  ansible.builtin.raw: gv_gitlab
  register: ssh_command_output

- name: Print response of ssh command
  debug:
    msg: "{{ ssh_command_output }}"

- name: run command through lish console
  ansible.builtin.raw: ls -lah
  register: ssh_command_output

- name: Print response of ssh command
  debug:
    msg: "{{ ssh_command_output }}"
```

Above hangs on first task. It seems when lish switches to the console ansible just sits there for ever.

I tried various things, like issuing linode name in `ansible_ssh_common_args`, or adding timeout and ignoring error in hope that next task will pick up ssh connection with console already initiated. Sadly, I can't get this to work.

Is there any way you may be aware of which would allow me to issue commands through lish?
