### ISSUE TITLE
[Bug]: Delete DNS record example is wrong in documentation

### ISSUE THREAD

**Issue by maximouche** [linode/ansible_linode#462]
### Ansible Version

2.15.5

### Ansible Configuration

NA

### Effected Components

Documentation (https://github.com/linode/ansible_linode/blob/main/docs/modules/domain_record.md) says
```
- name: Delete a domain record
  linode.cloud.domain:
    domain: my-domain.com
    name: my-subdomain
    state: absent
```
but type and target attribute are required to properly delete a record.

### Expected Behavior

Documentation should provide a valid example to delete a dns_record

Doc should target and type for the delete example :
```
- name: Delete a domain record
  linode.cloud.domain:
    domain: my-domain.com
    name: my-subdomain
    type: 'A'
    target: '127.0.0.1'
    state: absent
```

### Actual Behavior

Current example is wrong

### Steps to Reproduce

Test the current example in the doc
