### ISSUE TITLE
[Bug]: linode.cloud.domain_record does not work, is not idempotent

### ISSUE THREAD

**Issue by brad2014** [linode/ansible_linode#521]
### Ansible Version

2.17.0

### Effected Components

linode.cloud-0.26.0 domain_record

### Expected Behavior

I expect this task to create a DNS record "_cardavs._tcp IN SRV 0 1 443 host.example.com":

```yaml
    - name: Service records
      linode.cloud.domain_record:
        domain: example.com
        state: present
        service: carddavs
        protocol: tcp
        type: SRV
        target: host.example.com
        port: 443
        priority: 0
        weight: 1
```

I expect this would work if either the name is present, or the service+protocol are present, but not both.  I expect that 
`{ name: "_carddavs._tcp" }` and `{ service: "carddavs", protocol: "tcp" }` are equivalent.

I expect that if the task is executed when the DNS record already exists, it would report OK and do nothing.

### Actual Behavior

The task fails with error:

```
parameters are required together: name, type
```

After adding `name: ""` to workaround this error, the task succeeds with "status: changed".  However when repeated, the task does not report "status: ok", it repeats the update and reports "status: changed".

### Steps to Reproduce

1) Run the above task, notice it fails.
2) Add `name: ""` to the task.  Notice it succeeds.
3) Run the task again.  It should report OK, but it tries to update the domain_record again.

**Comment by brad2014** [comment]
Upon additional experimentation it appears a complete workaround is to set the name to duplicate the service and protocol:
```yaml
- name: Service records
      linode.cloud.domain_record:
        domain: example.com
        state: present
        name: _carddavs._tcp
        service: carddavs
        protocol: tcp
        type: SRV
        target: host.example.com
        port: 443
        priority: 0
        weight: 1
```

The result is both correct and idempotent.  So the only unexpected result is the service and protocol have to be specified twice.
