### ISSUE TITLE
[Feature]: append firewall rule on firewall

### ISSUE THREAD

**Issue by wouter-evolane** [linode/ansible_linode#610]
### Description

Running example playbook will result in firewall rule1 to dissapear from the firewall and rule2 to be the only one enforced.
I'm looking for a way to not be required to repeat the entire existing firewall config

### New/Affected Components

 linode.cloud.firewall

### Example Ansible Config

```
- name: test linode firewall
  gather_facts: false
  hosts: localhost
  tasks:
    - name: Create a Linode Firewall1
      linode.cloud.firewall:
        label: "test_linode"
        rules:
          inbound:
          - label: "test1"
            addresses:
              ipv4:
              - "1.1.1.1/32"
            description: "test1"
            ports: 1
            protocol: TCP
            action: ACCEPT
          outbound_policy: ACCEPT
          inbound_policy: ACCEPT
        state: present
    - name: Create a Linode Firewall2
      linode.cloud.firewall:
        label: "test_linode"
        rules:
          inbound:
          - label: "test2"
            addresses:
              ipv4:
              - "2.2.2.2/32"
            description: "test2"
            ports: 2
            protocol: TCP
            action: ACCEPT
        state: present
```
