### ISSUE TITLE
[Bug]: linode.cloud.domain_record is not idempotent

### ISSUE THREAD

**Issue by macno** [linode/ansible_linode#635]
### Ansible Version

ansible [core 2.17.5]

### Ansible Configuration

CALLBACKS_ENABLED(/ansible/ansible.cfg) = ['community.general.slack', 'community.general.opentelemetry']
CONFIG_FILE() = /ansible/ansible.cfg
DEFAULT_HOST_LIST(/ansible/ansible.cfg) = ['/ansible/inventory']
DEFAULT_REMOTE_USER(/ansible/ansible.cfg) = ansibleusr
HOST_KEY_CHECKING(/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/ansible/ansible.cfg) = /usr/bin/python3

### Effected Components

domain_record

### Expected Behavior

playbook runs every time without error nor changes (except the first time)

### Actual Behavior

playout fails after the first run with error `failed to create domain record: POST /v4/domains/[redacted]/records: [400] name: Record conflict - CNAMES must be unique`

### Steps to Reproduce

execute multiple times the following playbook
```
---
- name: Test linode.cloud.domain_record
  hosts: localhost
  become: false
  tasks:
    - name: Ensure CNAME record is aligned
      linode.cloud.domain_record:
        domain: example.com
        name: smtp
        type: CNAME
        target: mail.example.com.
        ttl_sec: 1800
        state: present
```
