### ISSUE TITLE
[Bug]: linode.cloud.domain_record 'state: absent' does not delete the record

### ISSUE THREAD

**Issue by macno** [linode/ansible_linode#636]
### Ansible Version

ansible [core 2.17.5]

### Ansible Configuration

CALLBACKS_ENABLED(/ansible/ansible.cfg) = ['community.general.slack', 'community.general.opentelemetry']
CONFIG_FILE() = /ansible/ansible.cfg
DEFAULT_HOST_LIST(/ansible/ansible.cfg) = ['/ansible/inventory']
DEFAULT_REMOTE_USER(/ansible/ansible.cfg) = ansibleusr
HOST_KEY_CHECKING(/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/ansible/ansible.cfg) = /usr/bin/python3

### Effected Components

domain

### Expected Behavior

the record is deleted

### Actual Behavior

the record is not deleted

### Steps to Reproduce

run this playbook
```
---
- name: Test linode.cloud.domain_record
  hosts: localhost
  become: false
  tasks:
    - name: Ensure CNAME record is aligned
      linode.cloud.domain_record:
        domain: example.com
        name: smtp
        type: CNAME
        target: mail.example.com.
        ttl_sec: 1800
        state: absent
```
